services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=quartodatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5434:5432'
