version: '3.8'

services:
  spring-boot-app:
    image: openjdk:17-jdk-alpine
    volumes:
      - ./target:/app
    ports:
      - "8098:8080"
    expose:
      - "8098"
    command: ["java", "-jar", "/app/MS-Quartos-0.0.1-SNAPSHOT.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/quartodatabase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: quartodatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret